##
## EPITECH PROJECT, 2019
## Libfox
## File description:
## Master Makefile
##

#
# Do NOT change the order of those
# It will likely break the makefile
##########################################
# ↓ Module name and sources
include ./makeinclude/module.mk

# ↓ Colors and text formatting
include ./makeinclude/format.mk

# ↓ Progressbar script
include ./makeinclude/progscript.mk

# ↓ Module configuration
include ./makeinclude/makeconf.mk

# ↓ Unit test libc wrappers
include ./makeinclude/wrappers.mk

# ↓ Various build configuration
include ./makeinclude/builconf.mk

# ↓ Receipes (for %.a and %.o)
include ./makeinclude/reciepes.mk

# ↓ Rules for making targets
include ./makeinclude/rules.mk
##########################################
