name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Criterion
      run: sudo add-apt-repository -y ppa:snaipewastaken/ppa && sudo apt-get -y update && sudo apt-get -y install criterion-dev
    - name: Install CSFML
      run: sudo ./.github/workflows/build_csfml.sh
    - name: Install GCovr
      run: sudo pip install gcovr
    - name: make and test libfox
      run:  make
